name = "digitalpigeon"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-19"
kv_namespaces = [
  {binding = "PIGEON", preview_id = "", id = ""}

]
